[package]
name = "lambda_example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
idemio = {path = "../../idemio"}
lambda_http = "0.17.0"
http = "1.3.1"
aws-sdk-lambda = "1.73.0"
aws-config = "1.6.0"
tokio = "1.48.0"
async-trait = "0.1.88"
